### ISSUE TITLE
stratospheric water vapor prod/loss option in pchem

### ISSUE THREAD

**Issue by sstrode** [GEOS-ESM/GEOSchem_GridComp#111]
@yvikhlya, Feng added an option to the pchem code (if H2O_ProdLoss: 1 in AGCM.rc) to allow pchem to update stratospheric water vapor using stratospheric water vapor production and loss rates (rather than zonal mean water vapor values).  The stratospheric water vapor production and loss rates were pre-calculated by Eric Fleming using the Goddard-2D model under the pre-industrial conditions.  We needed the new option for pre-industrial simulations since we don’t have stratospheric water vapor fields for the pre-industrial period.

**Comment by yvikhlya** [comment]
@sstrode I assigned myself to this issue and added a label `enchancement`.
