### ISSUE TITLE
GMI cannot be compiled with Bounds Checking on

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSchem_GridComp#30]
If you try and build GMI Chem with `-DCMAKE_BUILD_TYPE=Debug` and Intel, you get errors like this:
```
../src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/GMIchem_GridComp/GMI_GridComp/GmiChemistry/sulfur/aqu_sulfchem.F90(281): 
error #5561: Subscript #2 of the array SEMISS has value 0 which is less than the lower bound of 1
         snso2(:) = semiss(:, INSO2)
--------------------^
```
The issue seems to be due to `INSO2` and other parameters being set to 0:
https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/68bf4994b218025ea63bfe65d544c84ab1d797dc/GMIchem_GridComp/GMI_GridComp/GmiChemistry/stratTropMech/setkin_par.h#L140-L141

This change came in from #25.

If you look at `setkin_par.h` you will see:
https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/68bf4994b218025ea63bfe65d544c84ab1d797dc/GMIchem_GridComp/GMI_GridComp/GmiChemistry/stratTropMech/setkin_par.h#L60-L66

but in talking with @mmanyin, he seemed to indicate that while setting to 1 allows bounds checking, it also gives you the wrong answer! @mmanyin, can you comment more on this?

Perhaps, @tclune can think up a nice Fortran safe way of fixing this? I could fairly easily turn off bounds checking in GMI as a workaround, but it's better to fix the code correctly.

**Comment by mmanyin** [comment]
Part (perhaps all) of the problem is due to the fact that the "sulfur" subdirectory should have been deleted from the code.   I deleted it in my CVS tags a while ago.

**Comment by tclune** [comment]
I'm still having a great deal of trouble discerning what the code is _intended_ to do.    The value "0" may give the "right" answers, but it is clearly making out-of-bounds reference and the answers are not constrained by the standard.

It would appear that these parameters are meant to be distinct indices in higher-dimensional arrays that span a collection of species.   As such they should have unique values, and never should be 0.    My only guess is that someone thought "0" would somehow ignore those species.    Very much want to hear from Jules tomorrow.

**Comment by mmanyin** [comment]
The parameter values in setkin_par.h, in the context of offline GMI CTM, can be different depending on  the mechanism in effect  ( "strat/trop",  "strat/trop/aerosol",  etc.)  For example, if aerosols are not included, the aerosol indices are set to zero. The code **checks validity of the indices** by checking for non-zero.  This works fine unless you run the compiler in debug mode, and it flags some zeroes as bad array indices. If you try to quiet the compiler by changing all the zeroes to ones, then the **validity check** in the code does not behave correctly.

By the way,  the "strat/trop/aerosol" mechanism is not currently implemented in GEOS, but I have retained the aerosol indices, in case they are needed in the future.
