### ISSUE TITLE
Request for new release of GEOSchem_GridComp

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSchem_GridComp#34]
Dear @GEOS-ESM/chemistry-gatekeepers, 

I'd like to request a new release of `GEOSchem_GridComp`. I need it because the `develop` branch of `GEOSgcm_GridComp` is based off of releases of chemistry (and not a branch, currently v1.0.3), so to get the fixes for the debug build into my nightly GEOSgcm testing, I'll need a new release so I can then bug @sdrabenh with a PR. :)

**Comment by gmao-esherman** [comment]
Has this issue been resolved?

**Comment by mathomp4** [comment]
@gmao-esherman I can't imagine why not by now. I'll close it.
