### ISSUE TITLE
TR_GridComp as its own repository

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/GEOSchem_GridComp#51]
I would like to include TR_GridComp in GCHP as a git submodule so that GEOS and GEOS-Chem can use the same set of tracers. However, TR_GridComp is currently accessible only through GEOSchem_GridComp. Would you be open to moving it to a separate repo for communal use and development? This would be preferable to us doing a sparse checkout.

**Comment by tclune** [comment]
@lizziel 

For the moment, this is not going to happen.   Once we roll out mepo and see if it makes multi-repo work a bit less tedious, we can reconsider the balance between targeted granularity and complexity.

I think getting our GEOS-Chem dir to be a clone of your chem is a higher priority, followed by GOCART, and then maybe TR.   So for the moment your options are use 20th century techniques (copy the code and watch for changes) or to get a sparse clone of our whole chem repo.

**Comment by lizziel** [comment]
Sounds good. I'll close out this question.

**Comment by lizziel** [comment]
Following up on this question I asked last February, there is now progress towards moving TR_GridComp as its own repository. See issue https://github.com/GEOS-ESM/GEOSchem_GridComp/issues/102 for continuation of this discussion.
