### ISSUE TITLE
Add CircleCI to GEOSchem_GridComp

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSchem_GridComp#57]
I think I need to add at least a build against the GCM CI test for the Chem Grid Comp. I think I know how to do this based on the GCM GridComp. Might take a few attempts, but I can get there.

@mmanyin would you mind this? It would just be a build of GEOS with GNU.

**Comment by mmanyin** [comment]
@mathomp4  How often / at what point in the approval process is this run?  With every PR into CHEM Develop or Master?  And I assume that it will take 15 to 20 minutes each time?

**Comment by mathomp4** [comment]
@mmanyin It would be like the GCM GridComp. Every pull request would trigger a build (and every push to a PR). It wouldn't be required to pass (unless we wanted it) but after about 20 minutes, you'd hopefully see a successful build checkmark.

I'm going to start by doing like I do for GEOSgcm_GridComp. We checkout the pushed branch if it exists on *any* subrepo so if there is one of those 5 repository branches, hopefully we get all the needed fixes. We'll see what happens!

**Comment by mmanyin** [comment]
Okay, let's go with it

**Comment by mathomp4** [comment]
@mmanyin Well, the build is going along. My guess is if all is correct, the CI check in #58 should actually *fail* because I missed #56. We might need to rebase #58 and have it re-run once #56 is in.
