### ISSUE TITLE
Need to generate and copy setkin_chem_mech.txt___.rc into EXPDIR/RC

### ISSUE THREAD

**Issue by gmao-esherman** [GEOS-ESM/GEOSchem_GridComp#7]
GMI needs the file, setkin_chem_mech.txt___.rc, in its EXPDIR/RC. In the old GNU make version, it gets generated in GMIchem_GridComp/ and then copied to Linux/etc, and then the setup script copies it into RC.

In the new approach, it winds up in build/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/@GEOSchem_GridComp/GMIchem_GridComp/setkin_chem_mech.txt___.rc, but it never gets copied to RC﻿ by the setup script. It should probably go into install/etc.

**Comment by gmao-esherman** [comment]
Mike Manyin noted the following:
The missing file (setkin_chem_mech.txt___.rc) is just a copy of the file setkin_chem_mech.txt and it appears that it needed to be renamed to be an .rc file, so whoever did it decided to add ___ in the name too. The name with ___ does not need to be preserved. It would be most clear if the filename setkin_chem_mech.txt were used, but it would also be ok to swap in .rc for .txt.

**Comment by mathomp4** [comment]
@gmao-esherman It wasn't too difficult I think because of hard work @tclune did before hand. You need to do:
```cmake
foreach (file ${first_stage_files})
   install(
      FILES ${CMAKE_CURRENT_BINARY_DIR}/${file}
      DESTINATION etc
      )
endforeach ()
```
This installs:
```
Deposition_Registry___.rc 
Reactions_Registry___.rc 
GMI_Tendency_Registry___.rc 
setkin_chem_mech.txt___.rc
```
into `install/etc`.

**Comment by gmao-esherman** [comment]
What file does this need to be written to?

**Comment by tclune** [comment]
This goes into the CMakeLists.txt file in the top directory of the GMI grid comp.

Towards the bottom, you'll see similar lines of code for other .rc files.

**Comment by gmao-esherman** [comment]
Got it, thanks!
